# Generated by Django 5.1.1 on 2024-09-25 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_publisher_game_tags_game_youtube_user_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='publishergame',
            name='Game',
        ),
        migrations.RemoveField(
            model_name='publishergame',
            name='Publisher',
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(related_name='tag_game', to='home.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likes_user', to='home.game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='played',
            field=models.ManyToManyField(null=True, related_name='played_user', to='home.game'),
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=400)),
                ('publisher_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_comment', to='home.publishergame')),
            ],
        ),
        migrations.CreateModel(
            name='StreamGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewers_num', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.game')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.streamsite')),
            ],
        ),
        migrations.AddField(
            model_name='publishergame',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_game', to='home.game'),
        ),
        migrations.AddField(
            model_name='publishergame',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_game', to='home.publisher'),
        ),
    ]
