# Generated by Django 4.2.16 on 2024-09-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_game_youtube_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomment',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$dwHBwx8Fppb5WU6adjfG34$Gf3Git/0YwnJXlV91CMUfnKZcvnBqeEyrA6IKNOmB2U=', max_length=128),
        ),
    ]
