# Generated by Django 5.1.1 on 2024-09-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_publisher_game_tags_game_youtube_user_likes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="publishergame",
            name="Game",
        ),
        migrations.RemoveField(
            model_name="publishergame",
            name="Publisher",
        ),
        migrations.RemoveField(
            model_name="user",
            name="login_id",
        ),
        migrations.AlterField(
            model_name="game",
            name="tags",
            field=models.ManyToManyField(related_name="tag_game", to="home.tag"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes_user", to="home.game"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$GyKcwjU6vTr2NyDbqbnFhL$RybPNiqjPQ1Lxk7kQzvlPcEzzWVOhY2we5IirROcCnY=",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="played",
            field=models.ManyToManyField(
                blank=True, related_name="played_user", to="home.game"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table="auth_user",
        ),
        migrations.CreateModel(
            name="GameComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(max_length=400)),
                (
                    "publisher_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pg_comment",
                        to="home.publishergame",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="publishergame",
            name="game",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publisher_game",
                to="home.game",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publishergame",
            name="publisher",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publisher_game",
                to="home.publisher",
            ),
            preserve_default=False,
        ),
    ]
