# Generated by Django 5.1.1 on 2024-09-25 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_user_options_remove_publishergame_game_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="publishergame",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publisher_game",
                to="home.game",
            ),
        ),
        migrations.AlterField(
            model_name="publishergame",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publisher_game",
                to="home.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default=
                "pbkdf2_sha256$870000$S4RSIe0l63TE5WJuYCp1hU$o1Mg2iN25uCnqKCQjqZhjtO/GXH3Pi1dpeYmkDUk0EU=",
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="StreamGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewers_num", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.game"),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.streamsite",
                    ),
                ),
            ],
        ),
    ]
