# Generated by Django 4.2.16 on 2024-09-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_gamecomment_datetime_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishergame',
            name='review_score',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
