# Generated by Django 4.2.16 on 2024-09-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_publishergame_review_score_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_src',
            field=models.URLField(null=True),
        ),
    ]
